name: Run Tests

on:
  push:
    branches:
      - e2etesting
  pull_request:
    branches:
      - e2etesting

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      Xvfb:
        image: dorowu/ubuntu-xfce-vnc:latest
        ports:
          - 5900:5900

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r project/requirements.txt
        playwright install

    - name: Check Python version
      run: python --version

    - name: List installed packages
      run: pip list

    - name: Run tests
      run: pytest project/tests
      env:
        DISPLAY: ":99"
